{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "61eae374_09d5f0d2",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 5020
      },
      "writtenOn": "2023-09-21T22:55:16Z",
      "side": 1,
      "message": "The tests should clear in the next run. The earlier failure was due to a timeout.",
      "revId": "4163c3cb7acd971b6ccc554eeff030a153b99af9",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    }
  ]
}