{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "f3917f9c_11291e8f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 31957
      },
      "writtenOn": "2024-03-06T00:42:09Z",
      "side": 1,
      "message": "Looks like the failure is unrelated to the patch?",
      "revId": "76c8790d0eb16b7f4635623ca0ab06223b629b5d",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e9eb6ad4_4960d4ea",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 5020
      },
      "writtenOn": "2024-03-06T20:49:44Z",
      "side": 1,
      "message": "\u003e Looks like the failure is unrelated to the patch?\n\nUnlucky timing. It looks like one of the instances was rebooted and used before it had all of the data. I reran this. If you follow the link and log in, you should now see a \u0027Retrigger\u0027 link in the left column (unless someone already triggered it).",
      "parentUuid": "f3917f9c_11291e8f",
      "revId": "76c8790d0eb16b7f4635623ca0ab06223b629b5d",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "5970c9e4_74fe10a0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 5020
      },
      "writtenOn": "2024-03-06T20:49:44Z",
      "side": 1,
      "message": "Sorry, I forgot to post my draft last night.",
      "revId": "76c8790d0eb16b7f4635623ca0ab06223b629b5d",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    }
  ]
}