{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "7ac080fc_a6d20b78",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 31957
      },
      "writtenOn": "2023-09-12T18:37:37Z",
      "side": 1,
      "message": "Hi James, there\u0027s an x86 failure for this patch, it doesn\u0027t look like this was caused by the patch itself? Especially given that the following one did pass the tests",
      "revId": "bd84c85cffad7b66e1de4a304237c13713b751fc",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    }
  ]
}